title: "(Controlled) Randomness"
author: "Nikita Fomichev"
description: "Personal Blog about Experimentation and Data Science"

email: "nefomichev@gmail.com"
github_username: "nefomichev"
linkedin_username: "nefomichev"
theme: "minima"

markdown: CommonMarkGhPages
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
highlighter: rouge

rss: rss

plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
